banner:
  enable: true
  title: SC的心灵世界
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["Oranges", "GnBu", "Greys", "BuPu"]'
  opacity: 0.5
fireworks:
  enable: true
  colors:
    - '110, 139, 61'
    - '162, 205, 90'
    - '188, 238, 104'
colors:
  primary: '#669933'
  selection_bg: '#aed54c'
bg_image:
  enable: true
  url: https://i.328888.xyz/2023/02/25/EVduH.png
  dark: https://i.328888.xyz/2023/02/25/EVgPv.png
mode: time
reward:
  enable: false
wordcloud:
  enable: true